### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by Hujunxin** [yjhatfdu/Moe2_player#1]
作者你好，你的播放器很棒，请问如果想加入发射弹幕功能的话，我需要如何去做？ 谢谢。

**Comment by yjhatfdu** [comment]
其实我在danmakuManager里已经实现了，等两天我有时间我接上写个例子吧

**Comment by Hujunxin** [comment]
你好，请问例子的情况怎么样了？

**Comment by yjhatfdu** [comment]
已经加上了
